### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by Noctisdark** [lkesteloot/turbopascal#4]
I've been reading the source code for the compiler and I really congratulate you, never seen anything any neater, the code is self explanatory and readable and comment are doing a great job., Maybe I missed it when I got into the VM part because I do not know the theory ., I am looking forward to implement a Pascal Interpreter in C/C++ (Because I really want to make one), however I'm not sure about the type checking !, Any hints how to implement that ?, Thank you very much ^^

**Comment by lkesteloot** [comment]
Pascal compilers are very easy to write. The language was designed to be easy to implement. Niklaus Wirth (the author of Pascal) has a book called "Compiler Construction" that is supposedly very good (I've never read it). Don't worry at first about the type checking. Just start writing the compiler, and it will later be obvious where to do the type checking when you have to generate code.

**Comment by Noctisdark** [comment]
Thank you :D, never intented to post an issue. I was intended to reach you for a while, never know how :)
