### ISSUE TITLE
is new browser cannot run this any more?

### ISSUE THREAD

**Issue by kwccoin** [lkesteloot/turbopascal#8]
I click the online link it is a black screen.

I tried to the local version and encountered problem with the simplehttprequester and have to modify it to run http-server instead

```
# need to install the web server
# npm install http-server
python3 -m http.server 8000
# python3 -m SimpleHTTPServer
```

.\GO

Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [15/Jun/2020 08:34:56] "GET / HTTP/1.1" 200 -
::1 - - [15/Jun/2020 08:34:56] "GET /turbo.css HTTP/1.1" 200 -
::1 - - [15/Jun/2020 08:34:57] code 404, message File not found
::1 - - [15/Jun/2020 08:34:57] "GET /favicon.ico HTTP/1.1" 404 -
::1 - - [15/Jun/2020 08:36:18] "GET /unit.html HTTP/1.1" 200 -
::1 - - [15/Jun/2020 08:36:18] code 404, message File not found
::1 - - [15/Jun/2020 08:36:18] "GET /favicon.ico HTTP/1.1" 404 -

I can click the link and redirect to another web site about this and hence the server works.  Somehow just totally a rect. black screen

**Comment by lkesteloot** [comment]
Works for me on Mac Chrome and Mac Firefox. What browser and OS are you running? Do you see messages in the dev console?

**Comment by kwccoin** [comment]
Mac Safari

Got it run under Mac Chrome.  Thanks.  

PS: Trying to run the Turbo Pascal Bridge and migrate it to Javascript for fun.  Love this program!

**Comment by lkesteloot** [comment]
Weird, it works for me in Mac Safari as well.
